# Generated by Django 3.0.8 on 2020-08-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photourl',
            field=models.TextField(null=True, verbose_name='写真URL'),
        ),
    ]
